# Generated by Django 3.2.5 on 2021-08-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicles',
            new_name='Vehicle',
        ),
    ]
