# Generated by Django 3.2.5 on 2021-08-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_vehicles_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_no',
            field=models.CharField(max_length=255),
        ),
    ]
