# Generated by Django 3.2.5 on 2021-09-01 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_vehicle_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offence_commited', models.CharField(max_length=255)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.driver')),
                ('vehicle_involved', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Loader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=13)),
                ('age', models.CharField(max_length=50)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.vehicle')),
            ],
            options={
                'verbose_name_plural': 'Loaders',
            },
        ),
    ]
