# Generated by Django 3.2.5 on 2021-09-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_loader_offence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offence',
            options={'verbose_name_plural': 'Offences'},
        ),
        migrations.AddField(
            model_name='offence',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
